// src/lootTable.js
export const lootTable = [
  { category: "Оружие", name: "Urban Reaper (штурмовая винтовка)", power: "Высокая мощность" },
  { category: "Оружие", name: "Iron Fang (винтовка)", power: "Средняя мощность" },
  { category: "Оружие", name: "Rust Claw (пистолет-пулемёт)", power: "Средняя/ближняя дистанция" },
  { category: "Оружие", name: "Sandstorm (дробовик)", power: "Высокая мощность вблизи" },
  { category: "Оружие", name: "Pocket Viper (пистолет)", power: "Низкая мощность, быстрая" },
  { category: "Патроны", name: "5.56 Tactical Rounds", power: "Для винтовок" },
  { category: "Патроны", name: "7.62 Piercer Ammo", power: "Для мощных винтовок" },
  { category: "Патроны", name: "9mm Quickshots", power: "Для пистолетов и ПП" },
  { category: "Лечилки", name: "Combat Medkit", power: "Полное восстановление" },
  { category: "Лечилки", name: "QuickPatch", power: "Быстрое частичное лечение" },
  { category: "Лечилки", name: "Adrenaline Shot", power: "Медленное лечение + бафф" },
  { category: "Броня", name: "Kevlar Vest Mk I", power: "Лёгкая броня" },
  { category: "Броня", name: "Kevlar Vest Mk II", power: "Средняя броня" },
  { category: "Броня", name: "Titan Armor Mk III", power: "Тяжёлая защита" },
  { category: "Шлемы", name: "Scout Helmet", power: "Базовая защита" },
  { category: "Шлемы", name: "Raider Helmet", power: "Улучшенная защита" },
  { category: "Шлемы", name: "Juggernaut Dome", power: "Максимальная защита" },
];
